### ISSUE TITLE
How to go through each narration text and option?

### ISSUE THREAD

**Issue by kimmyparkw** [kimmyparkw/made-in-manhattan#3]
Is it easiest to create 2 separate arrays? Or create a class that has a narration text property and options property and then instantiate each step of the story?

**Comment by kimmyparkw** [comment]
I am not using the scratch.js file instead of the main.js file.

**Comment by kimmyparkw** [comment]
The way the function is set up right now, the loop is goin straight to the end of the list of the array, instead of showing up one by one.

**Comment by pmacaluso3** [comment]
When I clone&run it, I see that `userOptions` contains a string plus an array, so the nested forEach blows up when it tries to process the string. Should it be like this instead?
```
const userOptions = [
  ['I am ready to work'],
  ['go to the fabric store', 'pick up the dry cleaning'],
]
```
Either way, a nested loop is a good way to handle nested arrays, if you have data with 2 levels. But the way you describe the loop zipping to the end of the array, sounds like a common problem when using forEach. Try using a simple for loop instead?
